name: Deploy to npm

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build TypeScript files
        run: npm run build

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Publish to npm
        uses: js-actions/npm@main
        with:
          args: publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
